# Generated by Django 5.0 on 2024-01-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales_app', '0001_initial'),
        ('categories_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_app.category'),
        ),
    ]
