# Generated by Django 5.0 on 2024-01-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales_app', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_sales_app/media/uploads/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
